---
title: "Figure 1"
author: "MW"
date: "2024-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, echo=FALSE}
library(tidyverse)
library(maps)
library(ggmap)
library(raster)
library(ggsn)
library(cowplot)
```

This code creates the map in Figure 1. Load the data. 
```{r map_data}
ume_coords <- read_csv("Supplementary_data_2.csv")
```
Set the color scheme. 
```{r aesthetics}
season_colors2 = c("summer" = "white", "winter" = "black", "both" = "gray80")
site_colors2 = c("Oshine 1" = "black", "Nishi-honjo" = "black", "Ichiigawa" = "black", 
                   "Kiyokawa 1" = "black", "Kamihaya" = "black", 
                   "Kiyokawa 2" = "black", "Hirono" = "black", "Nagano" = "black", 
                   "Oshine 2" = "black", "Yamauchi" = "black", 
                   "Shimanose" = "black", "Higashi-honjo" = "red")
```


Designate area to map. 
```{r map_area}
height <- max(ume_coords$latitude) - min(ume_coords$latitude)
width <- max(ume_coords$longitude) - min(ume_coords$longitude)

sites_area = c(bottom = min(ume_coords$latitude)  - 0.85 * height,
               top    = max(ume_coords$latitude)  + 0.15 * height,
               left   = min(ume_coords$longitude) - 0.75 * width,
               right  = max(ume_coords$longitude) + 0.1 * width)
```

This code draws the map in Figure 1. 
```{r the_map}
japan_map = map_data("world", region = "japan") %>% 
  ggplot(aes(x = long, y = lat, group = group)) + 
  geom_polygon(color = "black", fill = NA) +
  xlim(129,146) + ylim(31, 48) +
  annotate("rect", xmin = sites_area[[3]], xmax = sites_area[[4]], 
          ymin = sites_area[[1]], ymax = sites_area[[2]], 
          alpha = 0, color = "red", lwd = 0.6) +
  theme(panel.background = element_rect(fill = "transparent"), 
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank())

sites_map = get_stadiamap(sites_area, zoom = 13, maptype = "stamen_terrain_background") %>% ggmap() + 
  geom_point(data = ume_coords, 
             aes(x = longitude, y = latitude, fill = factor(season, levels = c("summer", "winter", "both")), color = location),
             shape = 21, size = 4) +
  scale_fill_manual(labels = c("summer", "winter", "both seasons"), values = season_colors2) +
  scale_color_manual(values = site_colors2) +
  scalebar(x.min = 135.298, x.max = 135.418, y.min = 33.7, y.max = 33.8,
                            transform = T, location = "bottomright", dist_unit = "km",
                            dist = 5, st.dist = 0.05, st.size = 4) +
  theme(legend.position = c(0.2,0.82), axis.title = element_blank(), legend.text = element_text(size = 14),
        axis.text = element_blank(), axis.ticks = element_blank(), 
        legend.background = element_rect(fill = "transparent"), 
        legend.key = element_rect(fill = "transparent"), legend.title = element_blank(), 
        plot.margin = unit(c(1, 1, 1, 1), "inches")) +
  guides(color = FALSE) 

full_map = ggdraw(sites_map) + 
  draw_plot(japan_map, x = 0.18, y = 0.1, width = 0.3, height = 0.5, scale = 0.65)

north2(full_map, x = 0.582, y = 0.28, scale = 0.08, symbol = 1)
```

Jpeg file was created with the following code: 
```{r fig1_jpeg}
jpeg(filename = "Fig1.jpg", width = 186, height = 140, units = "mm", pointsize = 16, res = 400)
north2(full_map, x = 0.582, y = 0.28, scale = 0.08, symbol = 1)
dev.off()
```



