---
title: "Figure 6"
author: "MW"
date: "2024-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, echo=FALSE}
library(tidyverse)
library(ggtext)
library(vegan)
library(phyloseq)
source("helper_functions.R")
```

This code creates Figure 6. We use the OTU phyloseq object (cmnOTU) created in "Figure_2_and_S2_Rmd".  

Set the colors and labels we will use in the plots. 
```{r aesthetics}
class_colors = c("Generalist" = "black", "Summer_specialist" = "black", "Winter_specialist" = "black", "Too_rare" = "black")
class_fills = c("Generalist" = "#59f4a2", "Summer_specialist" = "white", "Winter_specialist" = "black", "Too_rare" = "#a259f4")
clam_labs = c("Summer_specialist" = "Summer\nspecialist", "Winter_specialist" = "Winter\nspecialist", "Generalist" = "Generalist", "Too_rare" = "Too rare")
```

Here we compare the OTUs found in the crop and mouth in both the summer and the winter. First we do a clam test on each sample type and use the data to create the plots. 
```{r orig_clams}
orig_clams = lapply(c("crop", "mouth"), function(v) {
  ps = cmnOTU
  ps2 = prune_samples(ps@sam_data$origin == v, ps)
  ps2 = prune_taxa(taxa_sums(ps2) != 0, ps2)
  sam_type = paste0(str_to_title(unique(ps2@sam_data$season)), "_specialist")
  if (taxa_are_rows(ps2)) {
    ps2@otu_table = t(ps2@otu_table)
  }
  df = clamtest(ps2@otu_table, ps2@sam_data$season) %>% 
    rowwise() %>% 
    mutate(Classes = ifelse(grepl("rare", Classes), 
                            "Too_rare", ifelse(grepl("Specialist", Classes), 
                                               paste0(str_to_title(str_split_i(Classes, "_", 2)), 
                                                     "_specialist"), "Generalist")))
  df$Classes = factor(df$Classes, levels = c(sam_type, "Generalist", "Too_rare"))
  cl_p = clam_plot(df1= df, title = v)
  cl_bp = clam_barplot(df, title = v)
  return(list("clam_df" = df, "clam_plot" = cl_p, "clam_barplot" = cl_bp))
})

names(orig_clams) = c("crop", "mouth")
```

This code creates Figure 6. 
```{r fig6}
grid.arrange(orig_clams$crop$clam_plot + theme(axis.title.x = element_blank()), 
             orig_clams$mouth$clam_plot + theme(axis.title = element_blank()),
             textGrob(orig_clams$crop$clam_plot$labels$x, gp = gpar(fontsize = 12), just = "top"), 
             orig_clams$crop$clam_barplot, 
             orig_clams$mouth$clam_barplot + theme(axis.title.y = element_blank()), 
             layout_matrix = rbind(c(3, 3, NA, 4, 4), c(3, 3, 5, 4, 4), c(NA, 5, 5, 5, NA), c(6, 6, 6, 7, 7)), 
             widths = c(0.25, 0.225, 0.05, 0.225, 0.25), heights = c(0.45, 0.1, 0.1, 0.35))
```


