---
title: "Figure 4"
author: "MW"
date: "2024-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, echo=FALSE}
library(phyloseq)
library(vegan)
library(ellipse)
library(tidyverse)
library(gghighlight)
library(gridExtra)
source("helper_functions.R")
```

Here are the color and shape schemes used. 
```{r aesthetics}
origin_colors = c("crop" = "#f4a259", "mouth" = "#bc4b51", "nectar" = "#648FFF")
bee_shapes = c("cerana" = 16, "mellifera" = 17)
```

Change counts to relative abundance for community composition analysis.
```{r naive_proportions}
cmn_prop <- transform_sample_counts(cmnOTU, function(x) {x/sum(x)})
```

Calculate PCoA values and add to sample data for easy ggplot figure. 
```{r pcoa_values}
cmn <- subset_pcoa(cmn_prop, d = "wunifrac")
```

Create PCoA plots. 
```{r pcoa_plots}
cmn_ps_pcoas = lapply(list(c("crop", "summer"), c("crop", "winter"), c("mouth", "summer"), c("mouth", "winter"), c("nectar", "winter")), 
                     function(x) {
                       return(plot_PCoA_w_highlight(cmn$physeq, paste(x, collapse = "_"), cmn$values, colorcode = "origin", shapecode = "bee_species", linecode = "bee_species", color_scheme = origin_colors, line_scheme = c("cerana" = "dashed", "mellifera" = "solid"), shape_scheme = bee_shapes, catg1 = "origin", grp1 = x[[1]], catg2 = "season", grp2 = x[[2]], op = "and"))
                     })

names(cmn_ps_pcoas) = unlist(lapply(list(c("crop", "summer"), c("crop", "winter"), c("mouth", "summer"), c("mouth", "winter"), c("nectar", "winter")), paste, collapse = "_"))

basic_theme <- theme(axis.title = element_blank(), title = element_blank(), legend.position = "none")
minimal_theme <- theme(axis.ticks = element_blank(), axis.text = element_blank())

fig4_plot =grid.arrange(cmn_ps_pcoas$crop_summer[[1]]$pcoa_w_ell + basic_theme + 
                 theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()),
             cmn_ps_pcoas$crop_winter[[1]]$pcoa_w_ell + basic_theme + minimal_theme, 
             cmn_ps_pcoas$mouth_summer[[1]]$pcoa_w_ell + basic_theme, 
             cmn_ps_pcoas$mouth_winter[[1]]$pcoa_w_ell + basic_theme + minimal_theme, 
             cmn_ps_pcoas$nectar_winter[[1]]$pcoa_w_ell + basic_theme,
             textGrob(paste0("Axis 1 (", round(cmn$values$Relative_eig[1] * 100, 1), "%)"), 
                      gp = gpar(col = "black", fontsize = 16)),
             textGrob(paste0("Axis 2 (", round(cmn$values$Relative_eig[2] * 100, 1), "%)"), 
                      gp = gpar(col = "black", fontsize = 16), rot = 90), 
             layout_matrix = rbind(c(NA, NA, NA, NA, NA, NA), c(NA, 1, 1, 2, 2, NA), 
                                   c(NA, NA, NA, NA, NA, NA), c(7, 3, 3, 4, 4, NA),
                                   c(7, 3, 3, 4, 4, NA), c(NA, 3, 3, NA, NA, NA), 
                                   c(NA, NA, 5, 5, 5, NA), c(NA, 6, 6, 6, 6, NA)), 
             widths = c(0.03, 0.44, 0.04, 0.02, 0.42, 0.05), 
             heights = c(0.05, 0.28, 0.02, 0.28, 0.023, 0.017, 0.29, 0.04))
samType_leg = Legend(at = c("crop", "mouth", "nectar"), title = "Sample type", title_gp = gpar(fontsize = 16, fontface = "bold"), legend_gp = gpar(fill = origin_colors[c(1,2,3)]), grid_height = unit(6, "mm"), grid_width = unit(6, "mm"), labels_gp = gpar(fontsize = 15))
species_shape_legend = Legend(at = c("Apis cerana", "Apis mellifera"), title = "Bee species", title_gp = gpar(fontsize = 16, fontface = "bold"), labels_gp = gpar(fontface = "italic", fontsize = 15), graphics = list(function(x, y, w, h) grid.points(x, y, pch = 1, size = unit(4.8, "mm")), function(x, y, w, h) grid.points(x, y, pch = 2, size = unit(4.8, "mm"))))
```

Jpeg figure 4 created using the following code: 
```{r fig4_jpg}
top.vp = viewport(layout = grid.layout(3, 3, widths = unit(c(26, 228, 26), "mm"), heights = unit(c(26, 304, 26), "mm")))
plot.vp = viewport(layout.pos.col = 2, layout.pos.row = 2, name = "plot")
splot = vpTree(top.vp, vpList(plot.vp))

jpeg(filename = "Fig4.jpg", width = 280, height = 356, units = "mm", pointsize = 16, res = 400)
pushViewport(splot)
seekViewport("plot")
grid.draw(fig4_plot)
draw(samType_leg, x = unit(0.33, "npc"), y = unit(0.19, "npc"), just = c("right", "bottom"))
draw(species_shape_legend, x = unit(0.345, "npc"), y = unit(0.12, "npc"), just = c("right", "bottom"))
grid.lines(x = unit(c(0.18, 0.205), "npc"), y = unit(0.145, "npc"), gp = gpar(lty = "dashed", lwd = 2))
grid.lines(x = unit(c(0.18, 0.205), "npc"), y = unit(0.13, "npc"), gp = gpar(lty = "solid", lwd = 2))
grid.text(label = "Summer", x = unit(0.3, "npc"), y = unit(0.98, "npc"), gp = gpar(fontsize = 16))
grid.text(label = "Winter", x = unit(0.75, "npc"), y = unit(0.98, "npc"), gp = gpar(fontsize = 16))
popViewport()
dev.off()
```


Beta diversity statistics. 
```{r betadiv_stats}
adonis2(UniFrac(cmn$physeq, weighted = T) ~ origin + season + bee_species, data = data.frame(cmn$physeq@sam_data))
adonis2(UniFrac(subset_samples(cmn$physeq, season == "summer"), weighted = T) ~ origin + site, data = data.frame(subset_samples(cmn$physeq, season == "summer")@sam_data))
adonis2(UniFrac(subset_samples(cmn$physeq, season == "winter"), weighted = T) ~ origin + site, data = data.frame(subset_samples(cmn$physeq, season == "winter")@sam_data))

cmn_pcoas_stats = lapply(list(c("summer", "origin"), c("winter", "origin"), 
                              c("crop", "season"), c("mouth", "season")), function(v) {
                                if (v[2] == "origin") {
                                  ps = cmn$physeq %>% filter_sample_data(season == v[1])
                                } else {
                                  ps = cmn$physeq %>% filter_sample_data(origin == v[1])
                                }
                              return(betadiv_stats(ps, parameter = v[2]))
                              })
names(cmn_pcoas_stats) = c("summer_samType", "winter_samType", "crop_season", "mouth_season")
```






